# Prepared Ubuntu 16.04 with stage2 bootstrapped
FROM awesomebytes/gentoo_prefix_ci_stage2_32b

# Let's get some specs of the machine that is running this job
RUN cat /proc/cpuinfo && cat /proc/meminfo && df -h

# Bootstrap Gentoo Prefix
RUN LATEST_TREE_YES=1 TESTING_PV=latest linux32 ./bootstrap-prefix.sh ${EPREFIX} noninteractive stage3

ENTRYPOINT ["/bin/bash"]
