name: Docker

on: 
  schedule:
    - cron: '00 13 * * 0,1,2,3,4,5,6'
  push: 
    branches: ["master","github-action"]
    # Publish semver tags as releases.
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ "master" ]
env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io

jobs:
  bootstrap_stage:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - dockerfile: ./bootstrap_stage/Dockerfile.prepare
            image: ${{ env.REGISTRY }}/gentoo_prefix_ci_prepare_32b
          - dockerfile: ./bootstrap_stage/Dockerfile.stage1
            image: ${{ env.REGISTRY }}/gentoo_prefix_ci_stage1_32b
          - dockerfile: ./bootstrap_stage/Dockerfile.stage2
            image: ${{ env.REGISTRY }}/gentoo_prefix_ci_stage2_32b
          - dockerfile: ./bootstrap_stage/Dockerfile.stage3
            image: ${{ env.REGISTRY }}/gentoo_prefix_ci_stage3_32b
          - dockerfile: ./bootstrap_stage/Dockerfile.emergesystem
            image: ${{ env.REGISTRY }}/gentoo_prefix_ci_emerge_system_32b
    permissions:
      contents: read
      packages: write
      # This is used to complete the identity challenge
      # with sigstore/fulcio when running outside of PRs.
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v2

      # Login against a Docker registry 
      - name: Log into ${{ env.REGISTRY }} 
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract Docker metadata Prepare
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ matrix.image }}
          flavor: latest=true
      -
        name: Build and push Prepare
        uses: docker/build-push-action@v4
        with:
          push: true
          context: ./bootstrap_stage
          file: ${{ matrix.dockerfile }}
          tags: ${{ steps.meta.outputs.tags }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          labels: ${{ steps.meta.outputs.labels }}

  package_stage:
    needs : bootstrap_stage 
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - dockerfile: ./package_stage/Dockerfile
            image: ${{ env.REGISTRY }}/gentoo_prefix_ci_gentoo_prefix_boostrapped_32b
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v2

      # Login against a Docker registry 
      - name: Log into Docker hub
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Extract metadata (tags, labels) for Docker
      # https://github.com/docker/metadata-action
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ matrix.image }}
          flavor: latest=true
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          context: ./package_stage
          file: ${{ matrix.dockerfile }}
          tags: ${{ steps.meta.outputs.tags }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          labels: ${{ steps.meta.outputs.labels }}
      # extract the zip file
      - name : Create .tar.lzma of /tmp/gentoo 
        run: docker run --entrypoint /tmp/gentoo/executeonprefix ${{ matrix.image }}:latest  "tar -c --lzma -f - -C /tmp gentoo" > ~/
      
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: gentoo_on_tmp.tar.lzma
          path: ~/gentoo_on_tmp.tar.lzma