name: Docker

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  push:
    branches: [ "master","github-action" ]
    # Publish semver tags as releases.
    tags: [ 'v*.*.*' ]

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io

jobs:
  package_stage:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - dockerfile: ./package_stage/Dockerfile
            image: ${{ env.REGISTRY }}/gentoo_prefix_ci_gentoo_prefix_boostrapped_32b
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v2

      # Login against a Docker registry 
      - name: Log into Docker hub
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Extract metadata (tags, labels) for Docker
      # https://github.com/docker/metadata-action
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ matrix.image }}
          flavor: latest=true
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          context: ./package_stage
          file: ${{ matrix.dockerfile }}
          tags: ${{ steps.meta.outputs.tags }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          labels: ${{ steps.meta.outputs.labels }}
      # extract the zip file
      - name : Create .tar.lzma of /tmp/gentoo 
        run: docker run --entrypoint /tmp/gentoo/executeonprefix ${{ matrix.image }}:latest  "tar -c --lzma -f - -C /tmp gentoo" > ~/
      
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: gentoo_on_tmp.tar.lzma
          path: ~/gentoo_on_tmp.tar.lzma